# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    tags: ['[0-9].[0-9]+.[0-9]+']
    branches: [master]


jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish
      env:
        VERSION: ${GITHUB_REF_NAME}
      run: dotnet nuget push "FastBot/bin/Release/FastBot.${VERSION}.nupkg"  --api-key ${{secrets.PACKAGE_PAT}} --source "https://nuget.pkg.github.com/swamp1820/index.json"
